//
// Created by 王柯 on 8/16/22.
//

#ifndef LEETCODE_2157_GROUPSTRINGS_H
#define LEETCODE_2157_GROUPSTRINGS_H

#include "solution.h"

class GroupStrings : public solution {
public:
    vector<vector<int>> adj;
    unordered_map<int, int> mm;
    bool *visited;

    int dfs(int node) {
        visited[node] = true;
        int res = 0;
        for (auto i : adj[node]) {
            if (!visited[i]) {
                res += dfs(i);
            }
        }
        return res + 1;
    }

    vector<int> groupStrings(vector<string> &words) {
        int groupNum = 0;
        int maxGroup = 0;
        int len = words.size();
        for (int i = 0; i < len; i++) {
            vector<int> tmpAdj;
            int mask = 0;
            int wordLen = words[i].size();
            for (int j = 0; j < wordLen; j++) {
                mask |= (1 << (words[i][j] - 'a'));
            }
            for (auto iter = mm.find(mask); iter != mm.end() && iter->first == mask; iter++) {
                tmpAdj.push_back(iter->second);
                adj[iter->second].push_back(i);
            }
            for (int j = 0; j < 26; ++j) {
                int newMask = mask ^(1 << j); // either add j or delete k
                for (auto iter = mm.find(newMask); iter != mm.end() && iter->first == newMask; iter++) {
                    tmpAdj.push_back(iter->second);
                    adj[iter->second].push_back(i);
                }
            }
            for (int j = 0; j < 26; ++j) {
                if ((mask & (1 << j)) == 0) // the char j exists, i.e., delete j
                    continue;
                for (int k = 0; k < 26; ++k) {
                    if ((mask & (1 << k)) == 0) { // the char k doesn't exist, i.e., add k
                        int newMask = mask ^(1 << j);
                        newMask = newMask ^ (1 << k);
                        for (auto iter = mm.find(newMask); iter != mm.end() && iter->first == newMask; iter++) {
                            tmpAdj.push_back(iter->second);
                            adj[iter->second].push_back(i);
                        }
                    }
                }
            }
            adj.push_back(tmpAdj);
            mm.insert({mask, i});
        }
        visited = new bool[len];
        memset(visited, false, sizeof(bool) * len);
        for (int i = 0; i < len; ++i) {
            if (!visited[i]) {
                int tmp = dfs(i);
                maxGroup = max(tmp, maxGroup);
                groupNum++;
            }
        }
        return vector<int>{groupNum, maxGroup};
    }

    void check() {
        vector<string> words = {"gupybltqmh", "wdtc", "ogli", "avnmizk", "upfwazt", "fsk", "xfsbwulr", "rwnp", "p", "u",
                                "x", "pfdkymhiat", "aoghblrutv", "kbql", "pleam", "zgoey", "gq", "wkcdumxlb", "zsfjq",
                                "pzforwvsu", "bjqsiucne", "erwmp", "cfknlr", "clspzbmiw", "bfu", "av", "rnulifpc", "ty",
                                "shfaeyzbv", "n", "prbnsg", "yzrvemka", "mxbia", "zhcbvdusty", "ywgs", "gmslxqfkzo",
                                "rbfjd", "bnshvclwrm", "rgacveyto", "dlbzsc", "fvaeyzb", "burojefxai", "mourt", "fyi",
                                "x", "zsidcgob", "z", "oax", "s", "pvrz", "zqmbntgs", "ctsk", "wrlgaez", "dabuxy",
                                "jyfot", "d", "dcyetk", "smi", "i", "n", "agrbon", "rtfqvxponj", "oqek", "pxdc",
                                "mqhzpnboy", "bilo", "bvxfi", "al", "pvj", "jdieqr", "jpcsoynvwg", "rspcuxntfa", "tdf",
                                "hpztywgui", "c", "kg", "uhxmbncrs", "fvdlg", "yjplmvg", "u", "kmabjp", "uzwxq",
                                "vqrzsewgi", "fpd", "nexbtaihl", "mot", "kmtw", "qgzb", "iqdmgwjxvo", "ujizmwvafr", "m",
                                "crkwudposv", "trolshmz", "k", "ztgf", "dlomz", "gx", "etckgo", "tsrdzekbai", "b",
                                "ugbp", "sxu", "vaoctdiybu", "mogd", "fu", "hm", "vk", "wmb", "ucvohfs", "wnhkatvb",
                                "wt", "lvnptrmo", "kvez", "iqlkeh", "d", "wsoze", "qjlchuz", "gpaxcsz", "l", "cd",
                                "zec", "zhx", "gaspf", "gdvp", "othixfauwv", "kfunzgtrd", "kshtl", "zvhwefk", "quho",
                                "lrncou", "ynvircxphf", "ykbnoduxeg", "gseh", "xfmeonp", "x", "dsfx", "jbri", "z", "zj",
                                "lqk", "u", "jrvfyeg", "tdqhls", "rw", "ym", "dy", "xkwdsou", "gczi", "jaur", "pabunkr",
                                "svxiqgnfc", "nj", "w", "nivyw", "weygqb", "kezogq", "uqod", "vxtmzsl", "zxhtd", "nk",
                                "efbwvz", "h", "ub", "mugrwdaxp", "kent", "ezlqfioksg", "jsxaol", "vlany", "f", "m",
                                "oeajv", "eotkdfcp", "dukfhq", "t", "lyzjxucbrv", "rlkyxcz", "vrt", "nmzc", "vyuioa",
                                "d", "p", "ksrlo", "ie", "dshtovj", "bc", "ye", "nbuxgqy", "crfdvajueq", "rucv", "we",
                                "dtyox", "miwulk", "pgjznvhwm", "zwj", "cfqgdx", "jx", "eifzr", "lsukbvty", "v", "z",
                                "ofkgaqysb", "uaypswgjrb", "gzo", "gdioblacz", "tmgluaip", "yjmx", "yv", "npf", "f",
                                "eyfj", "xfzjbwnv", "ph", "nl", "n", "f", "noilevqyj", "hqkyc", "ekogv", "zomkuhwjrc",
                                "mgecbafnj", "guisohr", "hevcxd", "wdqznjkfbe", "henwtougbi", "xqyeka", "lpovjxb",
                                "gyer", "qkbpwgrd", "hn", "aucmtlpw", "ikcszyqvge", "dpfj", "jb", "euoladrp", "m",
                                "jdwymantle", "dg", "rlpqhami", "dirfvp", "tpexjgaq", "cjhdtqplkx", "h", "bmcjsi",
                                "ijdgr", "xuo", "ovslkxqmw", "wzeyb", "yspzna", "plboghwyr", "kubgpf", "dxwhktiul",
                                "djr", "oebpnm", "fbhnupwj", "eh", "epbzgwr", "h", "bhw", "ysavtb", "j", "ncad", "zkoi",
                                "e", "bcahjml", "x", "yzogpwibqh", "fdupwti", "gwa", "jgwrz", "gsd", "snrx", "hbxfz",
                                "sbkol", "xaekr", "wgcexfbtpr", "obcaglsum", "ifgjzpqbac", "ifs", "fjqhxnse",
                                "bzemkfnyao", "tcwmpjgoar", "hw", "aqhvntwupg", "zcd", "o", "v", "jvw", "kfmhvgjyx",
                                "xmaeujdrgs", "f", "s", "n", "hekawlnrou", "sqrvti", "dvepzn", "may", "deai", "lg",
                                "enjuixvqd", "ysj", "xtgziyeua", "pxwun", "fhrw", "jkzvebyhil", "qrugyxt", "fwspykc",
                                "dbozq", "lohdwmgq", "sgpndotyub", "mgx", "ozsr", "zicswmhp", "mg", "lrif", "arjfhystc",
                                "ckjpq", "zetajx", "juvfkhwto", "qnbewpymcd", "uareopc", "lqihrnjov", "miwqe", "ib",
                                "mqwvd", "luwcqpfn", "revifla", "vebzsomr", "mtyjweu", "ykg", "qpzm", "qlotgexvn",
                                "qmwhji", "mushec", "vxeyrjnw", "wyf", "lubicpe", "ewvmi", "qslyoepmrv", "lqaijhxk",
                                "wxmylcv", "fsltrky", "kj", "pxfjil", "jguvs", "j", "f", "umdw", "wshjplbyaz",
                                "qurwnlipsc", "fhp", "hg", "pahq", "utg", "fmxyjk", "yobchxw", "wdvlcs", "lxwemdz", "e",
                                "aydv", "sqkej", "jahumgc", "tzlcqvewxb", "rh", "zqvp", "dsb", "v", "wbl", "bephozr",
                                "komyf", "wfop", "cdfb", "edirukmzcg", "mivh", "r", "irjpvu", "ehlgksdbf", "akvlgmbwf",
                                "jzlqafgn", "rt", "kbxrhejgsn", "nwrqzof", "cx", "qfj", "bvs", "jhvlydrgpi", "trzoy",
                                "hl", "mhrjk", "ic", "eaqnfiklm", "klqgywx", "drw", "jnmslhfvgi", "uehczgq", "uzcnpt",
                                "eymgb", "xgvmtqbsrh", "x", "ditzxlh", "simqpanto", "qblf", "hfzgjmi", "v", "pw",
                                "ywivcnfu", "qykecwfiur", "tkdhigy", "zo", "dn", "hnqe", "mky", "jwezokt", "fjoaudgpiw",
                                "fs", "cgmzxqwrd", "zdfhb", "qjihvnwom", "q", "ijavqcdg", "lscomfvnj", "zkevj",
                                "zutpoeix", "etgzjmd", "pjvksodeqc", "zfh", "egqazhdr", "sqkinybdj", "nahxtu", "ru",
                                "uicapn", "oajtkqscw", "ikndtg", "tgkys", "armlqtv", "wmgy", "mhwd", "bptqh",
                                "aywrsonzbe", "nse", "lkfrbsjq", "ntzcxvpea", "dxqrjf", "kyubjme", "gtn", "sdkvmuxyjh",
                                "krawu", "ltr", "u", "bsgma", "y", "rmjp", "wzmopbl", "yon", "aup", "jlhrtw", "hg",
                                "czij", "iu", "nhb", "qzlpeocxmd", "fzdcvgayt", "rfiwjdpvy", "qud", "kzul", "q", "iq",
                                "nwjvqdmcst", "dk", "dxcbou", "whnyqlcsuk", "vapb", "peo", "zj", "mskdwal", "rqstoj",
                                "ykgx", "rumhpgsv", "dq", "keuqgsabzt", "gmwisq", "gs", "c", "ncgwzx", "awrqlfdzec",
                                "gawlvizqmd", "sqnzilktvh", "habr", "b", "ujme", "fwdqvhrtgc", "paltuyzhwk", "bqgu",
                                "xpgvitjud", "nlbi", "s", "dcxw", "hac", "drjb", "sflnpqrc", "pfwo", "hsqrmjlvti",
                                "slwozcad", "idkv", "wiqt", "mnfwejl", "yngxbzte", "estfpvyak", "bpeytghm", "fdu", "i",
                                "klr", "onktwxla", "mxiqp", "pcz", "mb", "ozptlwej", "xbqvelcwid", "mhpwrlkcvd", "qus",
                                "nkzyhmcws", "v", "tsuznfq", "comnwk", "hybmpti", "jxutspezyh", "cefxz", "kzpcyxsbaw",
                                "yqan", "pcawhfng", "zxtdq", "vog", "tcieunvh", "qncftmubv", "xtr", "c", "c", "uzj",
                                "qovsbgeyc", "wpord", "gomspxhk", "gcmyazridh", "w", "ocpi", "ug", "dqvl", "tmiwo",
                                "tmk", "nif", "vzdpnam", "fxqdemo", "r", "dykpzuag", "wvrnt", "pm", "njptwfcvza",
                                "rxqcjwu", "od", "bhzsfetkwl", "iyrsoucb", "wpdiycq", "rhjusaldek", "ywulbr",
                                "gjsicubey", "zg", "x", "vjs", "dlsey", "xcfri", "queinmd", "npjhv", "vsbhmdk",
                                "qgkzasjboe", "vkbmnfaw", "yue", "f", "epbhg", "ptbze", "ocuztnih", "cin", "gcynzv",
                                "psjfc", "v", "hmnoviqky", "mgw", "virphftq", "e", "ujdtgvl", "otwhbr", "ck", "iflm",
                                "gbkzoaj", "mvwbh", "pxgwkcme", "gipxy", "b", "mpivfhzlr", "n", "xcqsuyk", "sblefdxwp",
                                "oubiqx", "hl", "gvupxw", "eiy", "gwbzvkua", "taqexkfvz", "f", "exvltighf",
                                "nbwvpghiso", "womvjcr", "kw", "fwpilonvc", "xkbhoaimw", "bjv", "pgxzd", "ws",
                                "zylrkvexf", "v", "uco", "d", "dufneack", "xbfsl", "fbequshv", "fwtadrsylm", "l",
                                "qcrfbvzo", "sdkwe", "qhsyatf", "zvabp", "xihabf", "vzjompxqd", "jloi", "myz", "q",
                                "wmcu", "lv", "klgwh", "bjtuamko", "sxobml", "ipwsfc", "wiovt", "nbjstfopx", "moxnb",
                                "tacj", "nms", "hqfpaylw", "crjtohb", "auvgscw", "nusjyceh", "tdyorlvse", "zjferbopdq",
                                "dlmr", "q", "jsreq", "kas", "avj", "qwbm", "nxf", "lxnqegds", "w", "lminub",
                                "murnihepj", "bsih", "owngh", "j", "gxckbitv", "p", "vxfjph", "ml", "opcuxsjb", "o",
                                "p", "jvqi", "tnaulc", "snpa", "uothaksv", "vtoy", "gxaeuf", "vdranhyefs", "zgby",
                                "nrehv", "qojupls", "bief", "ymq", "idbcnk", "ykbxzvos", "hxzc", "adqb", "bdcmuzktos",
                                "ow", "mrsgez", "wdxvl", "rtvuso", "logkbarzc", "fysvtrohln", "mnbgkufidy", "g",
                                "homgpznf", "tsgkm", "nhbdv", "dg", "nqxifmwpk", "irwqh", "pwymodls", "rezp", "hznsw",
                                "txoyisarwd", "iqczwkjan", "jeq", "jtwsaocyv", "vdb", "btly", "zmu", "smvoh", "qwd",
                                "gujmrifsyo", "cmein", "avo", "ptiywsz", "fjpbtzo", "upz", "npcudo", "suan",
                                "hzgklqxmis", "bkfs", "gokmjspb", "w", "kwemuiyp", "o", "ep", "esctfoaxu", "vcb", "r",
                                "avr", "svurmopa", "rldpi", "xrp", "amilhv", "jnf", "f", "osbfmulz", "qlzism",
                                "wlcjbmt", "ezf", "coxg", "hrpiuwvsq", "iwv", "wyfl", "mcaotniu", "edgwstoyb",
                                "mnzdsoix", "znrwkafdts", "lydhper", "twbnc", "caynf", "dtgwcisfy", "vkgn", "ivmd",
                                "vbxiyze", "cuf", "wrkgcpty", "vp", "anm", "ruzmwxyb", "xpwgckhiyu", "dbqnatle", "rgcl",
                                "amsxwepng", "hlbyqs", "alu", "k", "aiujhcpzxw", "pdk", "ijmlb", "fwiltq", "vwznbgaq",
                                "pjyid", "xhgyfl", "i", "ro", "wsymublva", "lgfkq", "vea", "uwblc", "fjmto", "pewxh",
                                "uifwgj", "csventphyu", "lnjmdy", "zro", "hzyvgs", "jgzokinv", "vywsothfl", "awpyjen",
                                "wzmbtsnvip", "cfuny", "utgl", "g", "m", "py", "k", "tkr", "jxdia", "rq", "lkvtmgo",
                                "s", "sxf", "xvrfwizmun", "fbxsng", "digafskmow", "fe", "epas", "buxoymqswg", "j",
                                "kxgwjqb", "phsi", "creoijnfst", "dotubgy", "artcf", "k", "etd", "ijrye", "pnztmd",
                                "srpnaobhq", "muoknsarx", "jwheyavuz", "ezpnckwrju", "dmaqkbtvs", "vwcmbos",
                                "oeukrfzti", "qy", "jrznk", "ylu", "xoirt", "gtbs", "olt", "sdmukwejpr", "ywxbzmodvf",
                                "prs", "hj", "zach", "vtqgjx", "hoiaduyzbk", "bxedyicvlq", "zf", "ubdsmpr", "hztjuf",
                                "fa", "zp", "bnxlpg", "vl", "pghiwf", "oqu", "vhcbw", "lmfwq", "tvmsbfoc", "uzwmnpyfi",
                                "prwbslvo", "lyvchiq", "i", "jdtopvkyzw", "hamcpvt", "btsegdjoq", "brc", "xop", "d",
                                "oyk", "patskuxeow", "frtzomsgqb", "h", "sdz", "lzqfw", "gmewtulvy", "cie", "rqeza",
                                "vxuoiwkg", "ljsqmz", "usgyofe", "nm", "zlvuy", "j", "k", "owa", "osvikr", "citghqxw",
                                "brgcwojep", "vdjon", "x", "honjvmg", "sfkelzobjg", "uk", "imfsowztq", "jvwerqg",
                                "lirhqtzm", "usjahvgmrd", "iqhwrey", "reidxv", "jnyceq", "ukeb", "oejsilhtcx", "lotk",
                                "s", "te", "yquehnso", "xotirscgq", "wqzdmhocpi", "qmk", "hvemy", "nvqhzbiwad", "zkq",
                                "dyoftbiwc", "cgjlutymx", "lyaidecjr", "hbsl", "ztcvu", "ibc", "iyjsug", "ldoucmj",
                                "onsclhytxb", "s", "pgluairvj", "adohi", "pmg", "imnfzg", "ger", "fnvgmbask", "zg",
                                "pjiqfokwd", "rcgvseky", "eriquhyw", "yvxs", "oay", "vdylrge", "hisrqpty", "ogs",
                                "cmtexuohq", "lndpm", "ixgoqc", "bxihzkyu", "rkwzdculfy", "pu", "ecmvus", "j", "fgm",
                                "lk", "zdvtrka", "wzps", "uhn", "foayhxgmkb", "yndgctwrax", "rwlaompzf", "a",
                                "cqligyuzo", "xzgcajqtyu", "gft", "pnky", "gx", "ptxqen", "uagq", "xod", "duczg", "i",
                                "vsetzfd", "rwgnbqa", "bzst", "mjwxicoqyp", "cvnbiskqh", "oguiehxtv", "mhtrgoijdv",
                                "xcwr", "hpjio", "v", "you", "qf", "ua", "sabfitrj", "hjpligvbs", "zadprbkgc",
                                "cmshkvurf", "ozdka", "qlvmdphxak", "hcljipew", "vr", "czbn", "jmawgicn", "dtwi",
                                "hdplzrgsb", "uck", "dmsl", "amwxbdq", "rqkzig", "u", "mapviz", "zhluqejkrd",
                                "xihreoqbu", "u", "etxn", "fqdwrm", "bt", "slbe", "zfuljhe", "lnxqapz", "ymzr", "lgxw",
                                "fhuwcanyr", "qinmrbfoc", "c", "dmrncw", "pf", "bdqrsv", "odktnlbvif", "omryszh", "r",
                                "lpheomv", "vuaprxlt", "yexzfa", "ukrox", "ivezr", "rwfozgnxab", "hzgeqyrsbp", "xqbrgm",
                                "fueqca", "c", "gjnpdtmbc", "cxvyorq", "tjgybwmzx", "rehlvdkus", "hwlskcmnuy",
                                "lgmqxjkvou", "sohek", "nz", "ktwnzj", "pbmz", "zsjlqg", "uvtywdgjb", "r", "naek",
                                "djaif", "ptasorn", "uqi", "lbdf", "hzvsieljb", "tnpyxdgq", "pdgaj", "qxtandplmf",
                                "vum", "gxkzevdrb", "yasrgwhukv", "gkwaszje", "zdcl", "svghx", "bo", "wekitogahy",
                                "yfzwsvjr", "lkpyiqvgfs", "ktbyexg", "g", "wgradi", "v", "iq", "a", "bmsoyjwru",
                                "ygfdmihk", "rwezjm", "n", "hbe", "jcktxguw", "pjbdnqiwgv", "jcik", "hpt", "idz", "ot",
                                "wualjd", "gpbrnz", "dyzpucmn", "bezn", "nzuhrbc", "pbvai", "moahqz", "qyuhnbvo",
                                "irvapyud", "wdcstoufj", "tlpmujno", "zgxu", "vu", "shf", "xw", "fcd", "xlsapcqmkf",
                                "n", "ytqdizm", "o", "tufpnkomvw", "slzem", "yki", "sjnt", "xdgqub", "if", "e",
                                "jgvmwxabye", "mfpaovcql", "mnkiwtdbae", "rhuq", "atgyuz", "uetwmbniy", "zpw",
                                "jlentxv", "fdibplouwm", "sco", "ndpfhryb", "ngxhudw", "liej", "pfyjwlbez", "jrxup",
                                "yfwpqkdgo", "xg", "kaloixjzqm", "rdxh", "tcih", "ikcuote", "vum", "tpdyce", "apylhmzs",
                                "riy", "qc", "ytmzbhw", "yo", "hzanyjxvmf", "bnt", "zeclu", "rwnxoiqyb", "zxkjqlgpv",
                                "jyp", "dxparl", "atqyvsghj", "rvxlkwfcge", "lbku", "zkdsrtaqw", "pzh", "cime",
                                "ysdklpqgc", "yws", "w", "arwn", "hskmypng", "jxa", "uafhszjc", "modtqwh", "dglizbhrs",
                                "pko", "xviqgcnj", "sd", "fiwzu", "laqtesgdo", "ybhgkpc", "p", "swtfzilhd", "ty",
                                "ftcmy", "uwthnbpxvs", "njwzvbxq", "f", "kqaw", "aek", "fqjbnx", "r", "gifkbt", "c",
                                "gdjbxornea", "gpqcs", "tesur", "emad", "avhkq", "dosxe", "sgi", "ovbu", "iahzkopqu",
                                "zf", "fdytsl", "gezuk", "igxbmylfuw", "r", "biyt", "mtvd", "rbcznjvda", "odqherbz",
                                "lqfkgy", "drxwn", "jixmwtgoec", "uzjxthy", "dgc", "fn", "w", "zpkisabdxg", "ju",
                                "sifwqhnu", "opafic", "vgnub", "s", "ctyukf", "h", "otmqv", "k", "umozqhb", "oarghclpf",
                                "efcr", "kavzsulnyg", "ndrczofg", "b", "asgfwmcepb", "xqh", "kc", "cxqwvkf", "zihbglys",
                                "mlqryvnd", "upizjs", "cmirl", "vi", "iklzwmrh", "gby", "tdp", "tcpqu", "tbadyknrz",
                                "guiwca", "qae", "ayh", "mjrdwvibnt", "yt", "pd", "fcpnoweux", "mrkt", "cmbsefvwuk",
                                "itkjdf", "zcti", "ykxisle", "pslcidb", "cegxtj", "fisvgbcptz", "wsef", "quexnpcktj",
                                "dkvtej", "ifqecwkgds", "jnqdy", "iltobj", "qojrfzctnp", "rfioyzdhlm", "piekhn", "ptqd",
                                "ldwmesxcr", "gh", "d", "zcibdl", "isxgrwyz", "hqmndtg", "cmszhvbw", "tjwr", "bqtkwd",
                                "v", "xpvertngz", "fsd", "gdyl", "xdtsh", "qix", "zsbetc", "xwtzsiknl", "gqpn", "q",
                                "acn", "wubcqgzh", "hlokfbw", "vkq", "ip", "ucxohrmajg", "ojn", "g", "qu", "fycjkbtuml",
                                "mdyxvk", "ihczln", "aitjldfnbx", "twsjezufa", "kaclm", "nb", "rgwlbpyjto", "nxqaweljy",
                                "ksihpfyg", "isvd", "lgent", "dlmotqxuh", "i", "kgfze", "d", "vainkxorm", "lukfq", "zp",
                                "fnkqulwx", "wmcu", "psoecvxrn", "sjdxgva", "ufejyzsia", "sdvhwi", "gac", "cnvkzh",
                                "fbginpr", "ucaqotwd", "t", "nbcdpgv", "ohbpysvzla", "jgyimvonr", "cr", "naejdgsx",
                                "vtx", "lfboypdtc", "mtiylkhg", "j", "aljh", "su", "ctw", "jguoxmied", "oaxvwkinc",
                                "hax", "e", "jpyzxnqgkb", "udej", "yxvk", "rpcdlihwma", "gts", "upirmaeodf", "gkq", "r",
                                "crkv", "cxzbvdqn", "rcmqolva", "rxaz", "fcxkzdbjli", "ol", "mvqw", "saove", "hrp",
                                "vnixoyd", "fjkrvzwa", "olazdfqcjx", "aioyp", "xtnmdev", "e", "blswfqvxu", "xbjsotmn",
                                "nbzqhjv", "m", "r", "ozrqdemtj", "qnvmsrtwpd", "gjbeflt", "sijtdnubyl", "xoqa",
                                "jvprsb", "sf", "iynkcrudl", "zsvwbmt", "shrvtzmunx", "du", "ynhgue", "zrkxbvwt",
                                "ogxzsephf", "frut", "gihkz", "qsebn", "ksfa", "kdbxsu", "gdb", "wahxmivedn", "wmlxpt",
                                "hdp", "gcfrb", "xmdhtqyl", "flpzb", "tw", "kifx", "djn", "oayv", "oypmjrf", "sk",
                                "azgicfpu", "jelopnaz", "zjwyvu", "kzrofumygw", "kdhemr", "mjkzp", "dpeihu", "xc",
                                "mifyc", "sqyncea", "zxw", "ljhkfsywco", "cmfwx", "noyshazpj", "waqouz", "z", "atsjhq",
                                "d", "ida", "txlf", "sdk", "zerlsmiyx", "aktzdfenj", "se", "e", "lcha", "zid", "vqi",
                                "honr", "naybhv", "vifxme", "fwtsm", "eylidgns", "mlbja", "ht", "oidxbg", "rxe", "acij",
                                "jep", "oiwdptuze", "dhrez", "kpvfned", "hy", "qajouhny", "maqjo", "saoi", "rousw",
                                "ytxcfksw", "jacehvw", "trajskyz", "cdrbjynwz", "rpl", "ahk", "i", "obi", "u",
                                "ojrdxevs", "jbikxqtvs", "qnu", "h", "kt", "zyfscnkopb", "lm", "lxupsc", "jsqf",
                                "bscyiqng", "edvgbau", "z", "hnvtqgec", "wfh", "yihuwlg", "himkf", "lujqfotav",
                                "uyvogpbx", "tznulgjy", "l", "mwuhlkvta", "m", "asyzhd", "s", "iv", "sfkyqw", "g", "r",
                                "me", "wuofgmc", "du", "tqrev", "ldhgji", "atfunzjgl", "juwpy", "rimbq", "gd", "xqjamc",
                                "fagsxj", "acgfni", "ew", "dlzkf", "xg", "kwotryjvp", "yuniherd", "fnsiymtlhp",
                                "jviqoawgtx", "iaqvw", "k", "oezpyagr", "gdstjv", "cmjgsq", "nuybdxstzv", "kljw",
                                "hzqaudpe", "lsgvby", "zmnv", "p", "omnfivla", "cvbakjmwi", "crb", "g", "swirfgdchl",
                                "hn", "dak", "mw", "mtpnvhuz", "smwvub", "itdspv", "rvlxucopgb", "xuveb", "fcenitu",
                                "gh", "dvxrq", "peadxqwo", "dizfuvplko", "a", "w", "cnpx", "drlxnh", "a", "vskgaplhq",
                                "nbzhptfjr", "to", "tf", "iw", "pkzgtx", "njzsgxola", "aulovbgme", "qnte", "mshku", "p",
                                "sixqofp", "ma", "dm", "xhcw", "uig", "jtsnyfmed", "mojzielta", "repnkyiadv",
                                "cbnajoixvp", "rojgskxaib", "bjdwpc", "ypljbzrmog", "fuhmgrsy", "gamnlcfd", "op",
                                "olyga", "nwespa", "awr", "xgtehjb", "jam", "omdt", "vmhekzjonp", "hdy", "xvt", "igv",
                                "uwzlprqy", "ongsmpcarx", "t", "cwqemlvd", "euczvmtx", "lqwco", "dtexobfz", "ixhos",
                                "dzs", "bsjqr", "grkwienu", "odzbjfkw", "k", "vajphktlyq", "kgljtymope", "bq", "d",
                                "ydm", "jezpb", "abld", "rwc", "uzygosxaj", "rbqiehj", "ekpaujq", "gwknhztfb", "dyatu",
                                "lc", "lpqad", "ofwyp", "pwdgsemjuq", "blufnokhrz", "n", "jciek", "u", "ihdtuwsg", "a",
                                "snvcu", "vyokuzer", "dcponmagh", "rmi", "az", "nd", "gqutzilsa", "imf", "zchk", "btdz",
                                "wobikedsu", "pdokwi", "nrozvfkcb", "lfwxz", "lubrcwimx", "wvs", "x", "mnparzucbw",
                                "zgkhnubq", "qxyf", "qkgnzmyjvc", "meozt", "k", "wziedjru", "ltkfdx", "k", "gnmpauxdeq",
                                "zvxqgfdkem", "lnobvi", "yohz", "sdixyratkc", "rsgznj", "tamdkynoq", "dwkm", "la", "af",
                                "nieovsh", "pmzwty", "jarod", "mx", "bmuhe", "tvplszd", "nbqst", "gyn", "yzvhxekrt",
                                "v", "d", "ixteguhmd", "c", "fkitvnga", "jawpbyfi", "mk", "jibyzmnwah", "aurtdbyvq",
                                "ugzqpesvkw", "oyztrns", "kgjpbmz", "wo", "gwnvbesx", "mcn", "bwx", "g", "qyhsb", "ty",
                                "kjzmunt", "tsolbka", "ygiaj", "zgbkyeciul", "jcp", "u", "jimk", "lq", "wex", "a",
                                "wvnicm", "azgchys", "dhrpf", "jamhv", "vksgwjfop", "k", "mkv", "ykvb", "z", "qpjob",
                                "abdjfmq", "eigmy", "zexfiwjton", "akrc", "pvyqaf", "egb", "eyqbkhsp", "yqidknfx",
                                "pfwujtno", "lw", "fgmxyser", "dygohtizx", "a", "elhat", "lmcw", "f", "qoshvn",
                                "lbznthvq", "hktpfy", "bgxy", "sx", "aoujzrdb", "gdmpoxa", "sov", "zao", "tw", "iumzh",
                                "vrtqixh", "tdojsgr", "qclufn", "wnabvmxqp", "rboih", "b", "jxq", "gastm", "kobq",
                                "lnot", "g", "iofy", "kf", "ytf", "n", "me", "plckhfqzo", "vzwyru", "zmlxo",
                                "ktueqyifnx", "zqcivesb", "qm", "niku", "drb", "xdwtkncegl", "q", "phzgjicbq", "zokmwg",
                                "emkt", "pyrx", "qosln", "udh", "dhs", "hjaqwobype", "eltu", "dumvjncg", "y", "hpcz",
                                "qdhp", "abot", "anbt", "xotghndp", "loeymbt", "pibtrzhv", "htfnpwv", "rbl", "agjtpr",
                                "jau", "ot", "oaewdcx", "l", "acpyw", "sneoxyumha", "ukxrq", "ehbsydrpno", "tf",
                                "cvbnzw", "ipgxjr", "pytgabm", "tlaxdprc", "wpvfuqgayi", "vmia", "iztcq", "n", "fgac",
                                "lafcndbzuv", "myailt", "mhqnlvraw", "fsilutv", "ckzpagnj", "raqpc", "heu", "nkjpb",
                                "bu", "kdjcetxbq", "qavzodbgf", "tbge", "pqcb", "jmzu", "aiwhl", "hsjeg", "joy",
                                "tsjnlk", "kavnshiwj", "zpoe", "zfuik", "coxhuw", "bsayzrhxk", "honf", "xjz",
                                "cshgodefwz", "fmvjgzr", "dxgnjz", "z", "ct", "bvl", "mytdwjbpno", "gmwvlyc", "k",
                                "dwthq", "guhvjwzxfo", "eultijqcm", "g", "l", "dfwuzqhkt", "txj", "fxglptknsw",
                                "bngkcyjlif", "b", "eiuslhbqwn", "hcstbwxl", "ydpa", "tvhwfkspl", "mpxqbr", "drlbsnzuj",
                                "molfudh", "dnrulmpc", "zeqolwmg", "jxyov", "ywlx", "iyo", "rdtwmj", "zhidypwgxj", "dy",
                                "fbxvrjy", "yrl", "t", "kuqcnaxfe", "cuv", "gk", "tgicq", "f", "xrmo", "kdx", "mz",
                                "wxv", "baywpnzgc", "yberno", "hobejfswc", "yokzvbpqwt", "q", "kjnxifc", "ewa",
                                "vzeoktl", "d", "pbiwxonm", "zxws", "hmunrkb", "i", "coxmj", "mojahf", "rvcsexl",
                                "rbcpkgnhef", "kzvb", "pfr", "wdysegoc", "xkpb", "krvdt", "mclzgan", "jin", "wiv",
                                "ayqd", "ajhntoxmwd", "vex", "sgoyzwiv", "zamupcyed", "z", "xblszpc", "sfkwqo",
                                "drsvbcajt", "x", "vdhocezq", "qjazrpbge", "uribw", "rkwxgcq", "a", "smytfnhdri",
                                "krboxvinqt", "djnocvws", "spmgrl", "r", "jyu", "ymobqkxdng", "itpxdjv", "efxwa", "ovw",
                                "uy", "hqlxk", "pztye", "gr", "rwd", "zsvqe", "ryovkslh", "iedjc", "jwvnxohez",
                                "lnhivf", "m", "ymts", "hfokaiegjt", "utr", "cx", "wyzi", "ufiwzvg", "cgh", "ujcwim",
                                "ypsgdzolbw", "en", "mnvrxltch", "bq", "s", "t", "olmy", "kshye", "mo", "coasq", "kote",
                                "rkji", "ump", "em", "h", "kdmeayvfq", "r", "sf", "ck", "k", "tazu", "jvlwxo", "rinq",
                                "spmx", "zipusqkrv", "gdtqu", "nobqxrufd", "vfskgxyet", "gqya", "hoikenjv",
                                "tbsdfuicjq", "r", "pzbi", "au", "fapnmkoxe", "nypjrev", "bncqhwaksl", "e", "xphdtbyv",
                                "jwuvmefa", "zebqanotu", "gwmtvzc", "u", "ykuaog", "pmqkvau", "qeh", "lbytrfhngx",
                                "kwdq", "nlbqjo", "rctzhu", "arfbtxq", "svqjwnd", "m", "gqzcvmiyu", "ck", "joqm", "wj",
                                "eabqiyxp", "u", "qnerly", "qskzfwugtv", "vxyrcwumqd", "iptjbo", "ixde", "vekbrm",
                                "lsukn", "yohepnwxjt", "nvg", "enjhzxyt", "bx", "rplvkzq", "asx", "jfgdxclyp",
                                "xejbyafcq", "m", "vk", "kzlfaiew", "z", "nsluivegx", "twknpcqgj", "agmdiubzq", "oj",
                                "awqoiczf", "midakz", "lrf", "qp", "vj", "zkrmyuc", "p", "vs", "dkjfbsauiq", "fbhp",
                                "ltey", "qsa", "hmtbn", "pjeis", "cirptlw", "dxbt", "kzuciwl", "tkhdi", "kimxcdarqu",
                                "lxuaimrowe", "duxrmfpy", "nbazf", "scftv", "ymfqbjksl", "pd", "vtudfyzjg", "d", "yeon",
                                "il", "a", "dgp", "dgbukmzphc", "oxwtgvna", "qpfh", "lziexym", "xlkvy", "xz",
                                "tywmufjxhr", "loigh", "sgzuihvr", "r", "itmvunpyke", "dzwhnbe", "rsex", "gqpz",
                                "cfxhvgqsm", "fwk", "yiwvmzrb", "au", "utsdciqa", "duvolwzx", "vrfdan", "fmsekj", "wc",
                                "pi", "pyijls", "jwiovc", "wzdr", "wykut", "rxwofntag", "pnjrabzw", "hpn", "pvxkwzimyu",
                                "kphf", "ukdwjmg", "zwn", "kexwf", "yvenq", "vqohuasfx", "wty", "vjusmxlp", "qwrtf",
                                "oui", "awjfom", "coy", "lm", "ctqjges", "trhamwxy", "uamyez", "hpxqsgvmtw", "p",
                                "gsfb", "ipuzna", "r", "hsw", "gnpfxibs", "n", "uider", "kqfricgnjo", "lkeicgntxh",
                                "pegzou", "yqkar", "gbxluq", "fgwlvc", "tlqauf", "xwpyqr", "cje", "czkxgom", "ibp", "l",
                                "kqzh", "trzdcn", "avi", "zk", "of", "jnuixaczhb", "pv", "urzy", "pigwrk", "mfkctx",
                                "kvhrdspqot", "jhnw", "zbxctj", "p", "hbf", "nhfvwr", "br", "xdcjfwmhou", "zp", "d",
                                "wnfrcxyom", "gmljaeoi", "sjvm", "q", "ie", "ltsdoyjgxe", "axozd", "pwn", "iazxqcf",
                                "eykofnrpbm", "ihyzl", "cw", "xzgsm", "vhujeyfdw", "huzcnqxo", "qpjkyg", "fclnie",
                                "mshb", "bjr", "uecatb", "shgum", "j", "dqkrm", "wknrbgfid", "smeirnofw", "qwmn",
                                "lryo", "opwzkrsa", "p", "k", "dmxyef", "gtbwrcs", "ehg", "mg", "q", "t", "unm",
                                "tpydvmrcj", "q", "ql", "kobqd", "hvdf", "aqmveickju", "kqpxaybg", "xudib", "paium",
                                "u", "hertuwvqk", "njkpcmwazt", "kwloj", "qmehuoasvj", "jirftpnm", "zlkcbqwx",
                                "upgnxfc", "j", "rofgeicpsd", "sbojfk", "teqohl", "eyf", "z", "q", "xvihqysn", "uhxsd",
                                "bk", "l", "kzimlrbo", "bjodzgcuvf", "euwsarflkj", "unmbdqp", "v", "pdat", "lb", "y",
                                "pcmxfdn", "nqvex", "rnwax", "cbswp", "fmziaocsuv", "hsrq", "qhsaxtzcv", "axhmyjcogf",
                                "zug", "nos", "log", "pizgt", "dcjuhqw", "pztoknv", "zroce", "jv", "yxmrshb", "s",
                                "coypl", "vo", "hlm", "fmhgdev", "dfnj", "avxlnoegws", "rkemfxqog", "eqa", "lehvfr",
                                "gsdmnxz", "kabijlvsm", "armd", "btfpizgw", "jzbr", "xoh", "fybxmdarv", "glh", "s",
                                "wrfkdjiqn", "jysk", "andpfig", "vjc", "tixvb", "cosnpz", "otzwjis", "opfsj",
                                "qpjizmsw", "gpvr", "gmr", "lhtsixvc", "u", "kqbfd", "mecxt", "cwyejag", "am", "hbz",
                                "bqxgdf", "pjruyoq", "crd", "uco", "yuwpo", "vok", "zwcenuld", "gosy", "y", "ldui",
                                "zdykv", "yvnhqgo", "rkftpva", "mrgjdhzv", "gr", "zci", "m", "yscj", "ptzmao",
                                "bvzuqxao", "hjmicwgk", "bhx", "bsxvpgcmo", "cv", "anqse", "mipdczblse", "qasrf",
                                "ftsxcmoipu", "bxenuqfc", "pjeubrglhq", "dszmrbqf", "cviebdyzl", "ismdyghzo", "j",
                                "vekqgdytpu", "fu", "fcxrsjep", "kdjbhflu", "kqgontw", "rpsgdxueah", "piek", "dhayif",
                                "treosb", "oiqg", "lyef", "scko", "hj", "ntsfohj", "hcati", "vepnsdk", "s", "xkeslrncw",
                                "pfudomjris", "cgdnuholaj", "jxplbihf", "hcxmvqrnoj", "zypkgeoc", "dmrwkfqi", "fmqtguw",
                                "r", "bjsgnc", "rpu", "fecq", "mtej", "byk", "zkouy", "yvpzbnl", "nkwlh", "opyeshtjdg",
                                "l", "jvgp", "chl", "bojzxfnvmi", "adtn", "b", "cprfmqyva", "jxfrhkzp", "lpn",
                                "paxnlbj", "hgw", "w", "vbioycaxh", "rtpvcalo", "xsujbtey", "idv", "oavi", "wfnbruiveg",
                                "pkgwbrzyv", "ku", "hi", "x", "u", "fyqnj", "brnkjeuvyh", "mxb", "sau", "eln", "ycknvm",
                                "rh", "vjac", "wc", "abru", "ocjzkwnyx", "y", "liurvnsac", "asgmf", "ivp", "ozjdp",
                                "dcpoht", "rbudiywlm", "kqasvotyfh", "k", "gtqdbypw", "bvtupmr", "hgncpjaq", "jdfwmgus",
                                "ulwmtdsh", "nfmydplszj", "b", "aweyvxfscr", "tjxk", "cwxvzf", "vwsjhndua", "uygcfohv",
                                "xbjuan", "ryfqadcbtn", "q", "rcpibdjmu", "ghobsrt", "ksabcow", "fksgybrthc", "vkd",
                                "lkiof", "stiph", "chxsilg", "axolr", "fnd", "tbwzjxalc", "svuczmirjw", "lbpq", "dxsoz",
                                "cerfdkwy", "cxhva", "irsplydq", "apbkur", "eyownsv", "ldoayzg", "xl", "tygfeh",
                                "avugmwrk", "whyz", "w", "id", "xzcjm", "zvwfyhtq", "lmhktf", "zk", "vrxuqy", "sbakdf",
                                "jvmkc", "cxboe", "a", "adqsc", "kznybxam", "whfsovypjr", "nid", "sjtagbpduy",
                                "ivjpbyhf", "tden", "nox", "jpfwo", "kjmls", "ecurptinw", "gaqzc", "udv", "thxyfjovk",
                                "tadgyuj", "lbfr", "cslybk", "a", "mg", "omeri", "lswxv", "hoitjbnx", "rchgxz",
                                "zdxacw", "izmy", "tgnwvhm", "qmlfvkzj", "fw", "vydt", "n", "acrikp", "xwvlueb",
                                "ieqfpdjg", "qhr", "ponuevlq", "qbpdxa", "qt", "obalfkwqyd", "xhmjgsri", "ozq", "wcf",
                                "auqkzv", "ohfdnpt", "tndkelrgcv", "sj", "jn", "nvpobwmtl", "jihkwrm", "pqnwub",
                                "hjpusqbzk", "fbhsyxj", "vgueismzkr", "gjquf", "sthbod", "nmwgsolajh", "b", "p",
                                "eokpjfc", "afhkdglys", "boadhclmy", "mf", "ywztpf", "mja", "kdbz", "ho", "xio", "mtnd",
                                "wqr", "vcrytn", "coaydbvuwe", "saxbvmr", "muklcorsnf", "abt", "yznpulac", "ufqrwxz",
                                "ozucbhkyqt", "bmawqgso", "nxjbmc", "dnolrxwzf", "hdeyaoic", "hp", "stwmlvkd",
                                "ztbqaivxr", "mreyibavw", "qla", "bsyqriln", "qzoyrel", "lebgtuyovc", "iyz", "t",
                                "fspgzaon", "qb", "iwumyaxkcl", "vc", "qtmv", "ucngykzis", "dxuf", "qjipostkug",
                                "cqvgkzmyp", "gmns", "zjtmfq", "urgtde", "jxlywn", "iokxrpecn", "cmnalejzwq", "xrda",
                                "jf", "fjy", "itqkfwoa", "qfvsar", "ufymqig", "jrzbu", "zsvbdlumf", "imfdlsnr", "qbpr",
                                "d", "un", "joskgudf", "u", "aryt", "ncibotvpj", "av", "zoftjd", "cuibyxoalr",
                                "egytkusbdx", "gq", "ypkhezdrc", "nsioufj", "v", "otpjxlgnwd", "fkynvdxl", "lxf",
                                "yetkhfmj", "z", "xvi", "dspyz", "uiraslfpo", "zexgwbkync", "jt", "dmkqwxlj", "zvyrba",
                                "lu", "ozc", "zt", "hrjwtnyme", "gfzaodln", "fe", "sy", "uh", "kixpvc", "mnfdrog",
                                "cpzyeamd", "posh", "wupthbji", "tkcphnsovz", "rwkiez", "ehnzqtuby", "wapkdubcmv",
                                "zjhmrkw", "gioa", "uxafbew", "sqe", "qvz", "uefysqzci", "sntdgrom", "zakwmprge",
                                "fximyjndr", "kqozmbjafh", "pwsx", "spm", "vrnktxaemp", "nwsymgdzt", "frto", "otumlbx",
                                "igpj", "ufyqbzmkrs", "gjtvzh", "wlgd", "qdzvmpnie", "w", "tem", "v", "ajqrftnez",
                                "frcodib", "tbamyvcf", "qr", "vwdalmjkyn", "cvzr", "ckslqb", "sdqu", "plgymfwn",
                                "hojsl", "l", "diackbfyrz", "fwxzhtvol", "u", "edmilvk", "ovbnzs", "d", "ldga",
                                "gcjfzkuilw", "vnsy", "svlyzhjbe", "sndqhifl", "briphkov", "qmt", "lcbymv", "swkhz",
                                "tohupvkifl", "zopdtlwxve", "wav", "egow", "ohgkazwlct", "bnsgltzic", "qdlrf", "rkh",
                                "fhsmykvgp", "wosrkctagm", "mxtoasz", "f", "kbcohfg", "vmzpnfd", "xv", "pjmytc", "nz",
                                "bjvdap", "skaogqumf", "rknvxtqca", "ys", "x", "qikl", "eru", "wrzleumgh", "bmrytl",
                                "nqtjgd", "wzbgprouat", "qblukozw", "bs", "wfclonp", "olekzbcivu", "uolbrvp",
                                "dfqbztexr", "x", "vdq", "dkvm", "rv", "untvk", "rdnhsc", "kacsjhtgp", "apjvtrgmb",
                                "uwk", "ujlp", "eo", "o", "aitkc", "isub", "fsupdqbwv", "vum", "t", "efqwzt", "xuk",
                                "yotjvnbz", "gpxwniajyz", "cfy", "eyclzabh", "ribuv", "mbjrkw", "mfpczuv", "keta",
                                "qtfx", "emqh", "amjbplvktq", "unhvs", "re", "wsc", "igxd", "hcgfyjrpo", "uzbjsemf",
                                "jg", "nbudocrqk", "lwn", "zj", "xgardtzkf", "mzqcdr", "cgwlkm", "gox", "fbkyxozct",
                                "dvfbemxn", "mdvyafgt", "qh", "tunjlfrc", "cy", "iuszorjgva", "bgpdhweq", "jex",
                                "tkvswn", "zyc", "ced", "oiwgu", "irosd", "zlh", "oxplzibu", "dcutb", "mhnwcotxv",
                                "mizf", "jnrlyu", "n", "taj", "hfimtqxco", "oifzvjx", "sdcbagykrt", "gdqorvjhua",
                                "pjavtnwxc", "jwtbzrdpo", "uivewgqc", "tiawqofcuv", "fqynw", "rbucgol", "xeoag",
                                "lprfvd", "gwhif", "pntqavlbi", "lvpfneos", "eqwgpmuakv", "jol", "mcsego", "ahltrszc",
                                "hbs", "bmvantuywg", "erbzd", "u", "yjzh", "nzqacbf", "lafuv", "kpu", "rbqimn",
                                "kjuwexdbpz", "v", "luq", "sb", "z", "pzuwfya", "pujvbzcsi", "xejronacdt", "vscelpah",
                                "xab", "g", "zbnayidu", "sbuo", "xrfioqv", "mh", "eczv", "qrgfoycbsm", "nixqlpbwm", "o",
                                "eyajisc", "bhltpumyv", "ash", "u", "z", "tmubdkly", "vj", "lzeawrmx", "ujkyqgd", "gnk",
                                "rphz", "wy", "zd", "oqckgrpf", "ovjdirxcmf", "orbfhsqnzg", "xbncuqio", "f", "pkwq",
                                "zfqbghnomd", "fopaqjvzlh", "nzgfbweky", "vykj", "rqu", "kzge", "zbfscpon", "ngjswaolq",
                                "xmawe", "rkc", "imukgozt", "w", "ujbxdzct", "oz", "tmgqalxdis", "ubaj", "q", "iemjnrk",
                                "wyfgk", "bwdiqxfr", "iogdl", "p", "ifrwhlcu", "uvlagi", "lcgrnkdvzt", "wsqvnxpcih",
                                "q", "ufnepj", "lfvo", "wbqo", "derl", "rgoc", "gkxopyq", "tcqoj", "ahr", "df",
                                "utahimnb", "rwkvgax", "qzbvnw", "pid", "bktigr", "idbrqo", "narpkq", "fjbnw",
                                "uzljdncps", "ofkgwadhnz", "js", "jeoxmi", "at", "mrxz", "huqsgboi", "strnm",
                                "xnbmfpae", "tzd", "petzvlkdrq", "e", "p", "xcud", "pcimnbd", "eyhip", "vofbdkga",
                                "bewrjna", "esogvxwdfl", "gfykxsj", "qxwzektdr", "regpbulw", "oy", "n", "lgroy", "gnk",
                                "ychp", "mevrtzh", "alrf", "jedn", "clfuvakwm", "zjkwx", "gidymhacnf", "ezsahf", "ipn",
                                "pu", "aibtnwz", "ziqblajrot", "u", "koyug", "dpsifye", "efgsprxhz", "ueahpvbrkq",
                                "xwlncdsurk", "qjcbetkn", "pcmxl", "imrse", "dl", "dvka", "iavegbn", "lzg",
                                "fmvyrioxbn", "je", "dh", "fwz", "qprmglvxiu", "txsncgzi", "itg", "wms", "dwoe", "oym",
                                "zxkts", "udqcpygbaf", "fpuvb", "ruvm", "gmiupzlvdo", "phz", "qnefgjthbv", "jnmyb",
                                "wyv", "bai", "bv", "jgt", "kobvwj", "x", "qovsfcew", "xndcmwhek", "ebxris", "kf",
                                "pvlx", "cv", "pcrmgs", "j", "gzap", "nhld", "owgup", "idygzolse", "dbhgs",
                                "vztedawgsh", "phae", "wi", "eivk", "dtwonaxgqe", "fspl", "xcnfleorh", "vgcyk",
                                "inmotdyv", "l", "mlswhf", "erpdqhbgc", "hdu", "nw", "djhonuswc", "mtekjdagz", "gla",
                                "l", "tfcli", "bhjumfi", "leojpbvfsa", "fuhxyb", "jvyrigzpdt", "svxon", "peu",
                                "ceqktsh", "vz", "nitzp", "xbzasmn", "lhkdotv", "b", "luta", "lziekdatbh", "mya",
                                "fpkcymanw", "mthk", "cvjtbsl", "bhqf", "avjwbny", "dfxvu", "owz", "txdapflsj", "zorm",
                                "pvlifq", "usie", "evuhwjginl", "sgaj", "prvzd", "rf", "cjmlstoryq", "wgsufmeivh",
                                "yzpct", "jwt", "jxmoe", "hypvwekzd", "wzkpmal", "bnwdjalyz", "xkengp", "gt", "b",
                                "wqctsbnguv", "iljdz", "bxidljq", "mxskhjnc", "ps", "niyba", "nzkfesybow", "bmpfa", "x",
                                "qbxfkze", "zrdnhmsu", "i", "in", "kdfexght", "dfjb", "miy", "bqvarjpwen", "ovmckitdq",
                                "exabkzu", "hd", "brzke", "snoap", "up", "lufsdne", "p", "nrplbhj", "pqjymf", "qpuxboz",
                                "vmliajnoc", "ockqm", "ysackpbnfl", "ripgjne", "wioxncpbgq", "pxei", "gzwderb",
                                "lhaepfo", "zxqj", "jf", "xu", "erodgqvfu", "ndtbluchs", "bhm", "ep", "yf", "yadnkiwr",
                                "tzevmb", "hbxoadgtv", "qakv", "asquwzr", "dg", "taournimv", "fxg", "jmqyznh", "daj",
                                "bksr", "gunalymqh", "qdomiahf", "ftm", "poethfanr", "ipmakbgtex", "sl", "nbgdwfahp",
                                "pcbafhn", "qgbmtk", "xm", "gbyrkdacz", "u", "dvpyrscgj", "wfh", "jrtumwlf",
                                "bcnmxhvjao", "qim", "vaceqymb", "zvuhymgtr", "wifkjebz", "swayjurn", "xkvbunjlg",
                                "ynki", "kjxszpdh", "ylxmk", "zjncpshdtb", "syl", "n", "tnlwes", "nlrh", "o", "zri",
                                "pxj", "fpykdlo", "lueziqspdy", "fry", "cjunwfto", "ybqis", "hycwuavj", "exhtfsayvp",
                                "hriwtnu", "jvqtzghf", "rfamptzlkg", "kjz", "abfz", "u", "qrevy", "vdrhtqf", "xthqgc",
                                "dsqjkuazn", "pcyow", "mcelq", "j", "jevrgcih", "nmxui", "cuqv", "gwbtuo", "akcb",
                                "axg", "ejui", "sqvzgnt", "qn", "dmn", "qtvuyibfn", "hscnpdeu", "d", "ygxvoehq", "s",
                                "syag", "c", "fojnrxpqw", "dbr", "szh", "teklirgnmd", "txacbhrdl", "we", "amlnfiekj",
                                "j", "bjvidar", "vslwkdjoat", "wj", "dnbrai", "pj", "m", "vasfixen", "ryxwqmogfa",
                                "tazus", "no", "zgd", "ytin", "celhtxds", "wojphfiv", "pyegb", "of", "hmjnbow",
                                "gjnwqrek", "flbz", "hzlju", "lj", "g", "sw", "aswiyd", "ojuwathcq", "zhyuqfjcgb",
                                "tmvqhnxac", "toygrkahf", "oldwcnyxim", "o", "lhpa", "dinmpsb", "yzhwo", "vnertzd",
                                "azucvhf", "cpw", "kbirpgmyex", "dbs", "k", "wpaqmi", "strh", "noyrcws", "kuyrdmpbns",
                                "bieumdyx", "gvciyelj", "nruxcmdl", "mi", "ipqguwfylv", "wisl", "kucoz", "audbklrmiw",
                                "wvngkstya", "mybxgtlnfu", "ftzhl", "vugqcs", "mbrs", "xjcmnol", "q", "jwh", "ydwx",
                                "cfqmalwyik", "qm", "fwc", "eiaw", "uso", "q", "aszginvpr", "cdpayu", "pilkz", "nxmzl",
                                "d", "mzjnaytfo", "cxowfs", "izgo", "jf", "xymz", "tjd", "jhtifyv", "fzyanulxv",
                                "pxcbae", "b", "d", "nwe", "fxcj", "lwiypadfe", "fes", "gviy", "qampxo", "trpglivmo",
                                "z", "pobeintca", "dnszpktaw", "nh", "uhmgnke", "ye", "jyavhopxuc", "ya", "kefxnrvtm",
                                "chusdk", "orb", "t", "enlhvfwmu", "yapuztjq", "kypblaz", "cznxopd", "xnp", "ayc",
                                "xbj", "zmveihg", "bfpc", "flnwamo", "ibgsc", "xyqh", "jxqa", "rueqa", "bnfzky",
                                "ptfkzhemq", "bvp", "v", "h", "ymsatfuxqr", "czf", "bfghotux", "fzgnymlwox",
                                "xftnrdlpb", "pikf", "j", "xljotmp", "xft", "rmqzjulhe", "bwf", "efnrd", "jraoh",
                                "iebphunja", "kwvdost", "u", "bigowx", "kqzhnvu", "xsehtgwm", "q", "rsgnolpj",
                                "omhnsgqa", "uwyfvgsi", "c", "juym", "ngphzlvu", "xof", "hjcqa", "bpe", "xcdgjnra",
                                "kgyx", "irehpqjl", "r", "ekzxgv", "czpwifujvl", "qfdbvn", "wjd", "dzop", "zukrc",
                                "emiwfjcbdz", "fhs", "opxeh", "ndaoc", "ordb", "env", "mufts", "gk", "ojx", "gnbeis",
                                "xjbfl", "mlrdn", "wgo", "nvprcmif", "xtmc", "ymhgjxd", "d", "b", "yptvme", "jgl",
                                "ewtahzmxpu", "ldhjctwue", "zomiyap", "gk", "xaybo", "zuhmoinaq", "hnfym", "cksvadxq",
                                "jsfyixlzr", "mnwaxv", "sgm", "qfyjhubp", "czoydgjwu", "sdn", "jnkywxps", "sf", "ftm",
                                "n", "sfhpc", "haodvmeqt", "grxmbykt", "tlyxekwriq", "tklf", "qsvafjp", "yqjme", "btlx",
                                "upr", "fkrqwnv", "ihlzdbfxm", "wlhndmq", "xrfghs", "cgkq", "qurx", "fwauc", "xrj",
                                "zfnt", "yvusznw", "uzj", "qck", "s", "bjkyrcl", "laytz", "tfzpu", "qjuv", "cgevfyxo",
                                "btv", "y", "dhix", "ygthqm", "iz", "hyjuztdkm", "wsjnx", "ctye", "hzymg", "dgsmfcpuzj",
                                "mdva", "ompxlkjdi", "tqapijrnx", "h", "zkpxwf", "anwiel", "as", "p", "iszptdlfh",
                                "wjyx", "up", "wdmihuynr", "vsmu", "kjf", "yadxltsf", "gbpy"};
        cout << words.size() << endl;
        auto res = groupStrings(words);
        cout << res[0] << " " << res[1] << endl;
    }
};

#endif //LEETCODE_2157_GROUPSTRINGS_H
